CREATE TABLE IF NOT EXISTS states (
  state_code TEXT PRIMARY KEY, state_name TEXT NOT NULL, fee_cents INTEGER,
  form_id TEXT, form_name TEXT NOT NULL, portal_url TEXT NOT NULL, turnaround TEXT,
  registered_agent_rules TEXT, annual_report_due TEXT, annual_report_fee_cents INTEGER,
  franchise_tax TEXT, notes TEXT, sources TEXT, verified_at TEXT, version INTEGER DEFAULT 1);
CREATE TABLE IF NOT EXISTS sessions (
  session_id TEXT PRIMARY KEY, token TEXT UNIQUE NOT NULL, stage TEXT DEFAULT 'discovery',
  fields_json TEXT DEFAULT '{}', paid INTEGER DEFAULT 0,
  created_at TEXT DEFAULT (datetime('now')), updated_at TEXT DEFAULT (datetime('now')));
CREATE INDEX IF NOT EXISTS idx_sessions_token ON sessions(token);
CREATE TABLE IF NOT EXISTS filings (
  id INTEGER PRIMARY KEY AUTOINCREMENT, session_id TEXT NOT NULL, state_code TEXT,
  business_name TEXT, fields_json TEXT DEFAULT '{}', status TEXT DEFAULT 'docs_pending',
  created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS documents (
  id INTEGER PRIMARY KEY AUTOINCREMENT, session_id TEXT NOT NULL, slug TEXT NOT NULL,
  name TEXT NOT NULL, r2_key TEXT NOT NULL, size_bytes INTEGER,
  created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS payments (
  id INTEGER PRIMARY KEY AUTOINCREMENT, session_id TEXT NOT NULL, payment_id INTEGER,
  access_token TEXT, email TEXT, amount_cents INTEGER, status TEXT DEFAULT 'pending',
  paid_at TEXT, created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS id_captures (
  id INTEGER PRIMARY KEY AUTOINCREMENT, session_id TEXT NOT NULL, legal_name TEXT,
  dob TEXT, street TEXT, city TEXT, state TEXT, zip TEXT, confidence REAL,
  captured_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS agent_runs (
  id INTEGER PRIMARY KEY AUTOINCREMENT, filing_id INTEGER, status TEXT DEFAULT 'pending',
  log_json TEXT DEFAULT '[]', created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS etl_checks (
  state_code TEXT PRIMARY KEY, portal_url TEXT, last_checksum TEXT,
  last_fee_seen_cents INTEGER, checked_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS etl_alerts (
  id INTEGER PRIMARY KEY AUTOINCREMENT, state_code TEXT, alert_type TEXT,
  detail TEXT, created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS session_snapshots (
  id INTEGER PRIMARY KEY AUTOINCREMENT, session_id TEXT NOT NULL, stage TEXT,
  snapshot_json TEXT, created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS compliance_nudges (
  id INTEGER PRIMARY KEY AUTOINCREMENT, session_id TEXT NOT NULL, state_code TEXT,
  nudge_type TEXT, due_text TEXT, period_year INTEGER, surfaced INTEGER DEFAULT 0,
  created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS pii_sweeps (
  id INTEGER PRIMARY KEY AUTOINCREMENT, run_at TEXT DEFAULT (datetime('now')),
  scanned_count INTEGER DEFAULT 0, deleted_count INTEGER DEFAULT 0);

INSERT OR REPLACE INTO states (state_code,state_name,fee_cents,form_id,form_name,portal_url,turnaround,registered_agent_rules,annual_report_due,annual_report_fee_cents,franchise_tax,notes,sources,verified_at) VALUES
('WY','Wyoming',10000,NULL,'Articles of Organization','https://wyobiz.wy.gov','Online filings processed immediately upon submission. Mail filings: 3-5 business days after receipt (per Wyoming Secretary of State form instructions). Expedited (official cover sheet, Rev. 06/2026): Next Business Day $700; Same Business Day $1,400.','Every LLC must maintain a registered agent with a physical Wyoming street address (no PO boxes). The owner may serve as their own registered agent if they have a WY street address and are available during business hours; commercial registered agents are allowed. A signed Consent to Appointment by Registered Agent must be filed with the Articles.','Each year on the first day of the LLC''s anniversary month (60-day grace; entity subject to dissolution after that)',6000,NULL,'Fee $100 verified on official WY SOS instruction sheet. Annual license tax is $60 minimum OR $0.0002 x Wyoming assets, whichever is greater (assets <= $300k pay the $60 minimum). Online card payments add 2.4% (min $1). Expedited filing IS available (conflict resolved 2026-09-19): the official Expedited Filing Cover Sheet (Rev. 06/2026) offers Next Business Day service $700 (submit by 5pm MT) and Same Business Day service $1,400 (submit by 12pm MT). The older May 2022 instruction sheet''s ''Wyoming statutes do not allow for expedited filing at this time'' language is superseded.','["https://formfiles.justia.com/pdf/wyoming/0669/24.pdf (text of official Wyoming Secretary of State LLC filing instructions)", "https://bizee.com/llc/wyoming/filing-fees-requirements (fee cross-check)", "https://sos.wyo.gov/Forms/Business/General/ExpeditedFilingsCoverSheet.pdf (official Wyoming Secretary of State Expedited Filing Cover Sheet, Rev. 06/2026: Same Business Day $1,400, Next Business Day $700)"]','2026-09-19'),
('DE','Delaware',11000,NULL,'Certificate of Formation of a Limited Liability Company','https://icis.corp.delaware.gov','Regular filings approximately 10 business days (secondary sources). Expedited tiers per the official fee schedule: 24-hour $50; same-day $100; Priority 2 (2-hour) $500; Priority 1 (1-hour) $1,000 per document.','A Delaware registered office and registered agent are required. The agent may be an individual Delaware resident or a commercial registered agent authorized in Delaware. The owner may serve as their own registered agent only if they maintain a physical Delaware street address and are available during business hours.','No annual report filing for LLCs. LLC Annual Tax of $300 due June 1 each year.',30000,'Delaware LLCs pay a flat $300 Annual Tax (due June 1); they are not subject to the corporation franchise tax.','Formation fee raised from $90 to $110 under HB 400 (signed May 21, 2026), per the revised Aug 1, 2026 fee schedule — some third-party guides still show the old $90. Filing is typically done by uploading the signed Certificate of Formation to the state''s e-filing system or by mail to 401 Federal St., Suite 4, Dover, DE 19901. The $110 formation fee was independently re-confirmed 2026-09-19 by opening the official fee schedule PDF (Revised August 1, 2026: ''Formation – domestic $110.00'').','["https://corpfiles.delaware.gov/Fee_Schedule/AugustFee2026.pdf (official Delaware Division of Corporations fee schedule, revised August 1, 2026)"]','2026-09-19'),
('FL','Florida',12500,NULL,'Articles of Organization for Florida Limited Liability Company','https://efile.sunbiz.org','Online filings processed in approximately 4 business days (June 2026 secondary reports); mail filings take longer.','Every LLC must have a registered agent with a physical Florida street address (no PO boxes). The agent may be a Florida individual, a Florida business entity, or an authorized commercial registered agent service. The owner may serve as their own registered agent. The $25 registered agent designation fee is part of the $125 total.','Each year between January 1 and May 1. $400 late charge added after May 1 ($538.75 total); entity may be administratively dissolved if no report by 5:00 p.m. ET on the third Friday in September.',13875,NULL,'Total state cost $125 = $100 articles + $25 RA designation (per official fee table; form_id has no numbered ID). Optional: certified copy $30, certificate of status $5. Annual report fee $138.75 and May 1 deadline corroborated by multiple secondary sources citing Florida Statutes ss. 605.0212/605.0213.','["https://efile.sunbiz.org/llc_filing_help.html (official Florida Division of Corporations fee breakdown: Articles $100 + Registered Agent Designation $25 = $125)"]','2026-09-19'),
('TX','Texas',30000,'Form 205','Certificate of Formation - Limited Liability Company','https://direct.sos.state.tx.us','Online filings via SOSDirect processed the same business day under normal volume; mail filings take approximately 5-7 business days (secondary reports).','An LLC must maintain a registered agent AND a registered office address in Texas. The agent may be a Texas individual or a business entity authorized to transact business in Texas. The owner may serve as their own registered agent if they have a Texas street address. Failure to maintain a registered agent/office may result in involuntary termination of the LLC.','No Secretary of State annual report. Every LLC must file a Public Information Report and Franchise Tax Report with the Texas Comptroller each year by May 15.',0,'Franchise tax: no tax due if annualized total revenue is under $1,230,000 (2026 no-tax-due threshold, secondary source). Above threshold: 0.375% (retail/wholesale) or 0.75% of margin. Texas has no personal income tax.','Texas Express expedited tiers reported by secondary sources: 24-hour +$50; next-day +$500; same-day +$750 — not confirmed on an official page this session; mark as secondary. 2.7% credit-card convenience fee applies to online payments.','["https://www.sos.state.tx.us/corp/forms/instructions/205-boc-instructions.pdf (official Texas SOS Form 205 instructions: $300 filing fee)", "https://www.sos.texas.gov/corp/instructions/205.shtml (official Form 205 instruction page)"]','2026-09-19'),
('CA','California',7000,'LLC-1','Articles of Organization - Limited Liability Company','https://bizfileOnline.sos.ca.gov','Standard processing ~5 business days from receipt per the official CA SOS Submission Cover Sheet (REV 03/2022); submissions are reviewed in date order with online submissions given priority. The SOS publishes live per-filing-type dates on its Current Processing Dates page (last updated 2026-09-18). Formation filing is online only via bizfileOnline.','An ''agent for service of process'' is required: either (a) an individual residing in California with a California street address (no PO boxes), or (b) a registered corporate agent that has filed Form 1505 with the SOS. The owner may serve as their own agent if they are a CA resident with a street address.','Statement of Information (Form LLC-12): due within 90 days of initial registration, then every two years thereafter.',2000,'Annual minimum franchise tax of $800 payable to the Franchise Tax Board — owed every year whether or not the LLC earns revenue.','Formation filing is online only via bizfileOnline. $800 annual franchise tax is a state tax collected by the Franchise Tax Board (separate from the SOS). Name reservation: $10 for 60 days.','["https://www.sos.ca.gov/business-programs/business-entities/forms/limited-liability-companies-california-domestic (official CA SOS fee table: Formation - Articles of Organization $70; Statement of Information $20)", "https://bpd.cdn.sos.ca.gov/corp/pdf/amendments/corp-amdtstkna.pdf (official CA SOS Submission Cover Sheet REV 03/2022 on bpd.cdn.sos.ca.gov: standard processing ~5 business days from receipt; online submissions given priority)", "https://www.sos.ca.gov/business/be/processing-dates (official CA SOS Current Processing Dates; live per-filing-type dates, last updated 2026-09-18)"]','2026-09-19'),
('NY','New York',20000,'DOS 1336-f','Articles of Organization','https://www.businessexpress.ny.gov','Online filings return an emailed filing acknowledgement with receipt within minutes. Mail filings: approximately 3-5 business days (secondary reports).','New York law designates the Secretary of State as the default agent for service of process for every LLC; the Articles must include a service-of-process address to which the SOS forwards documents. An LLC may also name its own registered agent. The owner may serve as the LLC''s agent.','Biennial Statement every two years, due by the end of the LLC''s anniversary month.',900,NULL,'NY publication requirement: within 120 days of formation, publish notice in two newspapers (one daily, one weekly) designated by the county clerk, once a week for six consecutive weeks; file the Certificate of Publication ($50 fee) with the DOS. Failure to comply can suspend the LLC''s authority to do business. Publication newspaper costs vary widely by county (especially NYC).','["https://dos.ny.gov/articles-organization-domestic-limited-liability-company-0 (official DOS page: $200 filing fee for Articles of Organization under Section 203 of the LLC Law)", "http://dos.ny.gov/fee-schedules (official DOS fee schedule: Biennial Statement $9; expedited handling 24-hr $25 / same-day $75 / 2-hr $150)", "https://www.businessexpress.ny.gov/app/answers/cms/a_id/2443/kw/domestic%20LLC (official NY Business Express: publication requirement within 120 days; Certificate of Publication $50)"]','2026-09-19'),
('NV','Nevada',7500,NULL,'Articles of Organization','https://www.nvsilverflume.gov','Not confirmed on an official NV SOS page (genuine attempt 2026-09-19; no public processing-dates page located). Secondary reports (2026): online via SilverFlume ~1 business day; mail ~3-4 weeks processing (5-6 weeks total with mail time). Official expedite tiers on nvsos.gov forms pages: 24-hr $125, 2-hr $500, 1-hr $1,000.','Registered agent must be a Nevada resident individual or a commercial registered agent authorized to do business in Nevada, with a Nevada street address (no PO boxes). The owner may serve as their own registered agent if they are a NV resident with a street address.','Annual List of Managers/Members due each year by the last day of the LLC''s anniversary month. State Business License renewal due annually at the same time ($200).',15000,'No personal or corporate income tax and no franchise tax. Nevada Commerce Tax applies only to entities with over $4,000,000 in Nevada gross revenue (secondary source).','Fee is $75 for the Articles only, but formation effectively costs $425 at checkout because Nevada also requires the Initial List of Managers/Members ($150) and the State Business License ($200) — SilverFlume bundles all three. Ongoing annual cost: $150 (Annual List) + $200 (license renewal) = $350/year.','["https://www.nvsos.gov/sos/sos-information/forms-all-divisions/trademark-forms (official nvsos.gov expedite schedule: 24-hr $125, 2-hr $500, 1-hr $1,000 \u2014 same tiers apply to all filings)", "https://llcformationcost.com/nevada-llc-cost/ (cross-check: Articles $75, Initial List $150, Business License $200, verified 2026-05-31 from NV SOS)"]','2026-09-19'),
('CO','Colorado',5000,NULL,'Articles of Organization','https://www.sos.state.co.us/biz/FileDoc.do','Online filings are ''filed in real-time ... immediately processed after you receive your payment confirmation'' (official CO SOS Business FAQs, Q7). Colorado accepts business filings online only; the Articles of Organization has no paper option.','Registered agent required: an individual 18+ who is a Colorado resident, or an entity maintaining a place of business in Colorado (including foreign entities authorized to do business in CO with a usual place of business). The owner may serve as their own registered agent; an LLC may serve as its own registered agent.','Periodic Report annually, due within the 3-month window beginning the first day of the LLC''s anniversary month (e.g., formed Jan 10: due Jan 1 - Mar 31 the next year).',2500,NULL,'$50 filing fee verified on the official CO SOS Business Organizations Fee Schedule (rev. 7/1/2024): LLC Articles of Organization $50.00 online (paper n/a). Colorado has occasionally run temporary fee reductions in the past; $50 is the current scheduled amount. Periodic Report fee is $25 per the current official schedule (rev. 7/1/2024); the $10 figure from the 2019 press release is outdated.','["https://www.sos.state.co.us/pubs/info_center/fees/business.html (official CO SOS Business Organizations Fee Schedule, rev. 7/1/2024: LLC Articles of Organization $50.00 online; Periodic Report $25.00)", "https://www.sos.state.co.us/pubs/business/FAQs/filing.html (official CO SOS Business FAQs, Q7: online filings filed in real-time, immediately processed after payment confirmation)"]','2026-09-19'),
('GA','Georgia',10000,'CD 030','Articles of Organization','https://ecorp.sos.ga.gov','Per the official GA SOS Corporations Division filing-procedure doc (rev. 7/2025): the certificate of organization is usually sent within 5 to 7 business days for online filings and within 15 business days for paper filings (mail, hand-delivery, or paper-filed-online); heavy workload can stretch online filings to ~10 business days.','Registered agent must be a Georgia resident individual or a business authorized to do business in Georgia, with a Georgia street address. The owner may serve as their own registered agent.','Annual Registration each year between January 1 and April 1.',5000,NULL,'Online filing via eCorp is $105 total ($100 filing fee + $5 service charge); mail/hand-delivery is $110 ($100 + $10 paper service charge) — per the official GA SOS filing-procedure doc (rev. 7/2025). Annual registration is $50 + service charge online, due Jan 1 - Apr 1. Georgia has no franchise tax for LLCs. Expedited tiers (2-day +$100, same-day +$250, 1-hour +$1,000) reported only by secondary sources — unverified.','["https://www.northwestregisteredagent.com/wp-content/uploads/2018/07/Georgia-LLC-Articles-of-Organization.pdf (official GA Secretary of State Form CD 030 instructions: $100 filing fee)", "https://www.incauthority.com/blog/georgia-llc/ (cross-check: $100 filing + $10 online service charge = $110 online; $50 annual registration online)", "https://sos.ga.gov/sites/default/files/2025-07/corp-filing_procedure-limited_liability_company.pdf (official GA SOS Corporations Division filing procedure, rev. 7/2025: 5-7 business days online, 15 business days paper; online $105 = $100 + $5 service charge)"]','2026-09-19'),
('AZ','Arizona',5000,'L010.007','Articles of Organization','https://ecorp.azcc.gov','Per the official AZCC Corporations Division processing-times sheet (latest version published at the URL below, dated 2025-12-29): LLC new filings 2-4 business days expedited, 9-11 business days non-expedited. The ACC updates the sheet periodically; older secondary reports (30-35 days) are stale.','Arizona calls this officer the ''statutory agent'' (not registered agent). The LLC must have a statutory agent with an Arizona street address. The agent may be an Arizona individual or entity; the owner may serve as their own statutory agent. A signed Statutory Agent Acceptance must be included with the Articles.','Arizona LLCs have no annual report and no annual fee.',NULL,NULL,'Note: filings go to the Arizona Corporation Commission, NOT the Secretary of State. Official expedite options: regular expedited $85 total (+$35); Next Day $100; Same Day $200; 2-Hour $400. Arizona requires publication of the LLC in an approved newspaper (3 consecutive issues, within 60 days of ACC approval) — publication costs vary by newspaper; ACC no longer requires proof of publication to be filed.','["https://azcc.gov/docs/default-source/corps-files/fee-schedules/fee-schedule-llcs.pdf (official Arizona Corporation Commission LLC fee schedule, rev. 3/2026: Articles of Organization $50 regular / $85 expedited)", "https://www.findlaw.com/state/arizona-law/how-to-form-an-llc-in-arizona.html (cross-check: $50 filing fee; no annual report requirement)", "https://AZCC.GOV/docs/default-source/corps-files/document-processing-timesfca30daa36e34a5e96fcc66a29e4a456.pdf (official AZCC Corporations Division document processing times: LLC new filings 2-4 business days expedited / 9-11 business days non-expedited; sheet dated 2025-12-29)"]','2026-09-19');
